<?php

namespace GeneralBundle\Repository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $nameStore
     * @return mixed
     */
    public function findStoreByName($nameStore){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.id
                FROM GeneralBundle:Store s
                WHERE s.nom LIKE :nameStore'
            )
            ->setParameter('nameStore', '%'.$nameStore.'%')
            ->getResult();
    }

    public function findStoreByOwner($idOwner){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s
                FROM GeneralBundle:Store s
                WHERE s.owner_id LIKE :idOwner'
            )
            ->setParameter('idOwner', '%'.$idOwner.'%')
            ->getResult();
    }
}
